/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

import java.awt.event.KeyEvent;
import java.lang.StringBuilder;

/**
 *
 * @author danil
 */
public class MainWindow extends javax.swing.JFrame {
    private Calculator calculator;
    private StringBuilder stringBuilder;
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        calculator = new Calculator();
        stringBuilder = new StringBuilder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        textField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        clearButton = new javax.swing.JButton();
        divideButton = new javax.swing.JButton();
        multiplyButton = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        plusButton = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        pointButton = new javax.swing.JButton();
        equalsButton = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        openBracketButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        closeBracketButton = new javax.swing.JButton();
        clearAllButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBounds(new java.awt.Rectangle(0, 0, 300, 400));
        setPreferredSize(new java.awt.Dimension(300, 400));
        setResizable(false);

        textField.setBackground(new java.awt.Color(204, 204, 204));
        textField.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        textField.setForeground(new java.awt.Color(51, 51, 51));
        textField.setToolTipText("");
        textField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField.setMinimumSize(new java.awt.Dimension(100, 180));
        textField.setPreferredSize(new java.awt.Dimension(270, 65));
        textField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldActionPerformed(evt);
            }
        });
        textField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldKeyPressed(evt);
            }
        });

        jPanel1.setAlignmentX(0.0F);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1.setLayout(jPanel1Layout);

        clearButton.setText("C");
        clearButton.setMinimumSize(new java.awt.Dimension(50, 50));
        clearButton.setPreferredSize(new java.awt.Dimension(50, 50));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(clearButton, gridBagConstraints);

        divideButton.setText("/");
        divideButton.setMinimumSize(new java.awt.Dimension(50, 50));
        divideButton.setPreferredSize(new java.awt.Dimension(50, 50));
        divideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel1.add(divideButton, gridBagConstraints);

        multiplyButton.setText("*");
        multiplyButton.setMinimumSize(new java.awt.Dimension(50, 50));
        multiplyButton.setPreferredSize(new java.awt.Dimension(50, 50));
        multiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel1.add(multiplyButton, gridBagConstraints);

        button8.setText("8");
        button8.setMinimumSize(new java.awt.Dimension(50, 50));
        button8.setPreferredSize(new java.awt.Dimension(50, 50));
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel1.add(button8, gridBagConstraints);

        button3.setText("3");
        button3.setMinimumSize(new java.awt.Dimension(50, 50));
        button3.setPreferredSize(new java.awt.Dimension(50, 50));
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        jPanel1.add(button3, gridBagConstraints);

        button5.setText("5");
        button5.setMinimumSize(new java.awt.Dimension(50, 50));
        button5.setPreferredSize(new java.awt.Dimension(50, 50));
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel1.add(button5, gridBagConstraints);

        button6.setText("6");
        button6.setMinimumSize(new java.awt.Dimension(50, 50));
        button6.setPreferredSize(new java.awt.Dimension(50, 50));
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        jPanel1.add(button6, gridBagConstraints);

        plusButton.setText("+");
        plusButton.setMinimumSize(new java.awt.Dimension(50, 105));
        plusButton.setPreferredSize(new java.awt.Dimension(50, 105));
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 3;
        jPanel1.add(plusButton, gridBagConstraints);

        button2.setText("2");
        button2.setMinimumSize(new java.awt.Dimension(50, 50));
        button2.setPreferredSize(new java.awt.Dimension(50, 50));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        jPanel1.add(button2, gridBagConstraints);

        pointButton.setText(".");
        pointButton.setMinimumSize(new java.awt.Dimension(50, 50));
        pointButton.setPreferredSize(new java.awt.Dimension(50, 50));
        pointButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        jPanel1.add(pointButton, gridBagConstraints);

        equalsButton.setText("=");
        equalsButton.setMinimumSize(new java.awt.Dimension(50, 105));
        equalsButton.setPreferredSize(new java.awt.Dimension(105, 105));
        equalsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 3;
        jPanel1.add(equalsButton, gridBagConstraints);

        button0.setText("0");
        button0.setMinimumSize(new java.awt.Dimension(100, 50));
        button0.setPreferredSize(new java.awt.Dimension(105, 50));
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        jPanel1.add(button0, gridBagConstraints);

        button1.setText("1");
        button1.setMinimumSize(new java.awt.Dimension(50, 50));
        button1.setPreferredSize(new java.awt.Dimension(50, 50));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel1.add(button1, gridBagConstraints);

        button4.setText("4");
        button4.setMinimumSize(new java.awt.Dimension(50, 50));
        button4.setPreferredSize(new java.awt.Dimension(50, 50));
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel1.add(button4, gridBagConstraints);

        button9.setText("9");
        button9.setMinimumSize(new java.awt.Dimension(50, 50));
        button9.setPreferredSize(new java.awt.Dimension(50, 50));
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        jPanel1.add(button9, gridBagConstraints);

        button7.setText("7");
        button7.setMinimumSize(new java.awt.Dimension(50, 50));
        button7.setPreferredSize(new java.awt.Dimension(50, 50));
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel1.add(button7, gridBagConstraints);

        openBracketButton.setText("(");
        openBracketButton.setMinimumSize(new java.awt.Dimension(50, 50));
        openBracketButton.setPreferredSize(new java.awt.Dimension(50, 50));
        openBracketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBracketButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(openBracketButton, gridBagConstraints);

        minusButton.setText("-");
        minusButton.setMinimumSize(new java.awt.Dimension(50, 50));
        minusButton.setPreferredSize(new java.awt.Dimension(50, 50));
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        jPanel1.add(minusButton, gridBagConstraints);

        closeBracketButton.setText(")");
        closeBracketButton.setMinimumSize(new java.awt.Dimension(50, 50));
        closeBracketButton.setPreferredSize(new java.awt.Dimension(50, 50));
        closeBracketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBracketButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(closeBracketButton, gridBagConstraints);

        clearAllButton.setText("CA");
        clearAllButton.setMinimumSize(new java.awt.Dimension(50, 50));
        clearAllButton.setPreferredSize(new java.awt.Dimension(50, 50));
        clearAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(clearAllButton, gridBagConstraints);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(textField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(textField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        
        textField.setText(textField.getText() + "7");

    }//GEN-LAST:event_button7ActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        
        textField.setText(textField.getText() + "0");
        
    }//GEN-LAST:event_button0ActionPerformed

    private void textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldActionPerformed

    }//GEN-LAST:event_textFieldActionPerformed

    private void textFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldKeyPressed
        
        String number = textField.getText();
        int length = number.length();
        
        char c = evt.getKeyChar();
        if(evt.getKeyChar()>'0' && evt.getKeyChar() <= '9') {
            textField.setEditable(true);
        } else {
            if(evt.getKeyChar() == '?' || evt.getKeyChar()=='_') {
                textField.setEditable(false);
                return;
            }
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE ||
                    evt.getExtendedKeyCode()==KeyEvent.VK_DELETE ||
                    evt.getExtendedKeyCode()==KeyEvent.VK_OPEN_BRACKET ||
                    evt.getExtendedKeyCode()==KeyEvent.VK_CLOSE_BRACKET ||
                    evt.getExtendedKeyCode()==KeyEvent.VK_MINUS ||
                    evt.getExtendedKeyCode()==KeyEvent.VK_PLUS ||
                    evt.getExtendedKeyCode()==KeyEvent.VK_ADD ||
                    evt.getExtendedKeyCode()==KeyEvent.VK_SLASH ||
                    evt.getExtendedKeyCode()==KeyEvent.VK_MULTIPLY ){
                textField.setEditable(true);              
            } else if(evt.getExtendedKeyCode()==KeyEvent.VK_ENTER) {
                equalsButtonActionPerformed(new java.awt.event.ActionEvent(this, WIDTH, "hello world"));
            } else {
                textField.setEditable(false);
            }
            
        }
        
    }//GEN-LAST:event_textFieldKeyPressed

    private void pointButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointButtonActionPerformed
        
        textField.setText(textField.getText() + ".");
    }//GEN-LAST:event_pointButtonActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed

    textField.setText(textField.getText() + "3");        
        
    }//GEN-LAST:event_button3ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        textField.setText(textField.getText() + "2");

    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        
        textField.setText(textField.getText() + "1");

        
    }//GEN-LAST:event_button1ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        textField.setText(textField.getText() + "6");

    }//GEN-LAST:event_button6ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        textField.setText(textField.getText() + "5");

    }//GEN-LAST:event_button5ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        textField.setText(textField.getText() + "4");

    }//GEN-LAST:event_button4ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        
        textField.setText(textField.getText() + "9");

    }//GEN-LAST:event_button9ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        textField.setText(textField.getText() + "8");

    }//GEN-LAST:event_button8ActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        String currentText = textField.getText();
        String newText =  "";
        if(currentText != null && currentText.length()>0 ) {
            newText = currentText.substring(0, currentText.length() - 1);
            textField.setText(newText);

        }
        
        
    }//GEN-LAST:event_clearButtonActionPerformed

    private void divideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideButtonActionPerformed
        textField.setText(textField.getText() + "/");

    }//GEN-LAST:event_divideButtonActionPerformed

    private void multiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyButtonActionPerformed
        textField.setText(textField.getText() + "*");

    }//GEN-LAST:event_multiplyButtonActionPerformed

    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        textField.setText(textField.getText() + "-");

    }//GEN-LAST:event_minusButtonActionPerformed

    private void clearAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllButtonActionPerformed
        textField.setText("");
    }//GEN-LAST:event_clearAllButtonActionPerformed

    private void openBracketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBracketButtonActionPerformed
        textField.setText(textField.getText() + "(");

    }//GEN-LAST:event_openBracketButtonActionPerformed

    private void closeBracketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBracketButtonActionPerformed
        textField.setText(textField.getText() + ")");
    }//GEN-LAST:event_closeBracketButtonActionPerformed

    private void equalsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsButtonActionPerformed
        
        String result = calculator.calculate(textField.getText());
        textField.setText(result);
        
    }//GEN-LAST:event_equalsButtonActionPerformed

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        
        textField.setText(textField.getText() + "+");
        
    }//GEN-LAST:event_plusButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.LookAndFeelInfo[] installedLookAndFeels=javax.swing.UIManager.getInstalledLookAndFeels();
            for (int idx=0; idx<installedLookAndFeels.length; idx++) {
                if ("Nimbus".equals(installedLookAndFeels[idx].getName())) {
                    javax.swing.UIManager.setLookAndFeel(installedLookAndFeels[idx].getClassName());
                    break;
                }
            }
                
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton clearAllButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton closeBracketButton;
    private javax.swing.JButton divideButton;
    private javax.swing.JButton equalsButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton multiplyButton;
    private javax.swing.JButton openBracketButton;
    private javax.swing.JButton plusButton;
    private javax.swing.JButton pointButton;
    private javax.swing.JTextField textField;
    // End of variables declaration//GEN-END:variables
}
